[package]
name = "monnapse/flow"
version = "0.1.1"
license = "Apache-2.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

<<<<<<< HEAD
[dependencies]
=======
[dependencies]
>>>>>>> 984328f5e0640851f75959a056bb2324d368861b
